<?php

return [

    'default_success_message' => 'Success',

    'default_error_message' => 'Error',

    'include_debug_info' => env('API_RESPONSE_DEBUG', false),

    'include_status_code' => env('API_RESPONSE_INCLUDE_STATUS_CODE', true),

    'keys' => [
        'success' => 'success',
        'message' => 'message',
        'data' => 'data',
        'errors' => 'errors',
        'meta' => 'meta',
        'status_code' => 'status_code',
    ],

    'pagination_keys' => [
        'current_page' => 'current_page',
        'per_page' => 'per_page',
        'total' => 'total',
        'last_page' => 'last_page',
        'from' => 'from',
        'to' => 'to',
        'path' => 'path',
        'links' => 'links',
    ],

    'openapi' => [
        'enabled' => env('API_DOCS_ENABLED', true),
        'app_name' => env('API_DOCS_APP_NAME', env('APP_NAME', 'API')),
        'app_logo' => env('API_DOCS_APP_LOGO', null),
        'title' => env('API_DOCS_TITLE', 'API Documentation'),
        'description' => 'API documentation auto-generated by Laravel API Response Builder',
        'version' => env('API_DOCS_VERSION', '1.0.0'),
        'route_prefix' => 'api',
        'docs_route' => 'api-docs',
        'theme_color' => env('API_DOCS_THEME_COLOR', '#10b981'),
        'default_theme' => env('API_DOCS_DEFAULT_THEME', 'auto'),

        'servers' => [
            [
                'url' => env('APP_URL', 'http://localhost'),
                'description' => 'API Server',
            ],
        ],

        'contact' => [],

        'license' => [],

        'security_schemes' => [],

        'versioning' => [
            'enabled' => env('API_DOCS_VERSIONING', false),
            'auto_detect' => true,
            'default_version' => env('API_DOCS_DEFAULT_VERSION', null),
            'versions' => [],
        ],

        'websocket' => [
            'enabled' => env('API_DOCS_WEBSOCKET', true),
            'url' => env('WEBSOCKET_URL', env('APP_URL', 'http://localhost')),
            'endpoints' => [],
        ],
    ],

];
