<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Success Message
    |--------------------------------------------------------------------------
    |
    | This value is the default success message that will be used when no
    | message is provided to the success response methods.
    |
    */

    'default_success_message' => 'Success',

    /*
    |--------------------------------------------------------------------------
    | Default Error Message
    |--------------------------------------------------------------------------
    |
    | This value is the default error message that will be used when no
    | message is provided to the error response methods.
    |
    */

    'default_error_message' => 'Error',

    /*
    |--------------------------------------------------------------------------
    | Include Debug Information
    |--------------------------------------------------------------------------
    |
    | When set to true and the application is in debug mode, additional
    | debug information will be included in error responses, such as
    | exception traces and file locations.
    |
    */

    'include_debug_info' => env('API_RESPONSE_DEBUG', false),

    /*
    |--------------------------------------------------------------------------
    | Include Status Code in Response Body
    |--------------------------------------------------------------------------
    |
    | When set to true, the HTTP status code will be included in the JSON
    | response body. This is useful for clients that cannot easily access
    | HTTP headers or for debugging purposes.
    |
    */

    'include_status_code' => env('API_RESPONSE_INCLUDE_STATUS_CODE', true),

    /*
    |--------------------------------------------------------------------------
    | Response Keys
    |--------------------------------------------------------------------------
    |
    | Customize the keys used in the API response structure. This allows
    | you to match your existing API conventions or standards.
    |
    */

    'keys' => [
        'success' => 'success',
        'message' => 'message',
        'data' => 'data',
        'errors' => 'errors',
        'meta' => 'meta',
        'status_code' => 'status_code',
    ],

    /*
    |--------------------------------------------------------------------------
    | Pagination Meta Keys
    |--------------------------------------------------------------------------
    |
    | Customize the keys used in the pagination metadata. This allows you
    | to standardize your paginated responses across all endpoints.
    |
    */

    'pagination_keys' => [
        'current_page' => 'current_page',
        'per_page' => 'per_page',
        'total' => 'total',
        'last_page' => 'last_page',
        'from' => 'from',
        'to' => 'to',
        'path' => 'path',
        'links' => 'links',
    ],

    /*
    |--------------------------------------------------------------------------
    | OpenAPI/Swagger Documentation
    |--------------------------------------------------------------------------
    |
    | Configure the automatic API documentation generation. The documentation
    | is generated from your routes and controller attributes.
    |
    */

    'openapi' => [
        // Enable/disable the documentation routes
        'enabled' => env('API_DOCS_ENABLED', true),

        // API documentation title
        'title' => env('API_DOCS_TITLE', 'API Documentation'),

        // API documentation description
        'description' => 'API documentation auto-generated by Laravel API Response Builder',

        // API version
        'version' => env('API_DOCS_VERSION', '1.0.0'),

        // Route prefix to scan for documentation (only routes starting with this prefix will be documented)
        'route_prefix' => 'api',

        // Documentation route path
        'docs_route' => 'api-docs',

        // Theme color for Swagger UI
        'theme_color' => '#3b82f6',

        // API servers
        'servers' => [
            [
                'url' => env('APP_URL', 'http://localhost'),
                'description' => 'API Server',
            ],
        ],

        // Contact information (optional)
        'contact' => [
            // 'name' => 'API Support',
            // 'email' => 'support@example.com',
            // 'url' => 'https://example.com/support',
        ],

        // License information (optional)
        'license' => [
            // 'name' => 'MIT',
            // 'url' => 'https://opensource.org/licenses/MIT',
        ],

        // Security schemes (optional)
        'security_schemes' => [
            // 'bearerAuth' => [
            //     'type' => 'http',
            //     'scheme' => 'bearer',
            //     'bearerFormat' => 'JWT',
            // ],
            // 'apiKey' => [
            //     'type' => 'apiKey',
            //     'in' => 'header',
            //     'name' => 'X-API-Key',
            // ],
        ],
    ],

];
